# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False, verbose_name='calendar_id')),
                ('date', models.DateField(verbose_name='date')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('place', models.CharField(max_length=127, verbose_name='place')),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_time', models.TimeField(verbose_name='end_time')),
                ('class_id', models.IntegerField(null=True, verbose_name='class_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False, verbose_name='class_id')),
                ('class_name', models.CharField(max_length=128, verbose_name='class_name')),
                ('professor', models.CharField(max_length=33, verbose_name='professor')),
                ('credit', models.IntegerField(verbose_name='credit')),
                ('homepage', models.CharField(max_length=512, null=True, verbose_name='homepage')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('classtime_id', models.AutoField(primary_key=True, serialize=False, verbose_name='classtime_id')),
                ('weekday', models.IntegerField(verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_time', models.TimeField(verbose_name='end_time')),
                ('location', models.CharField(max_length=128, verbose_name='location')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class', verbose_name='class_id')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False, verbose_name='semester_id')),
                ('semester_name', models.CharField(max_length=32, verbose_name='semester_name')),
                ('start_day', models.DateField(verbose_name='start_day')),
                ('end_day', models.DateField(verbose_name='end_day')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Semester', verbose_name='semester_id'),
        ),
    ]
